### PR TITLE
Handle large queues with a disk backed queue

### PR DESCRIPTION
**Pull request by tomlea**
We've been using starling very heavily here at Reevoo, and have made some substantial changes to it.

In this pull request we have:
- Fixed the delete command (the 2nd option is optional according to the memcache spec)
- Added a disk backed queue for when the in memory queue size gets above 10,000 messages.

This prevents memory consumption bringing the box to it's knees when a poller outage causes millions of messages to queue up.

Our experimentation showed that a starling queue with more than 100k messages in a single queue would grind to a halt.

Adding the disk backed queues for everything after the first 10k, then loading the disk backed store back in again 10k at a time kept the queue responsive at all times.

We've been using this in production, processing well in excess of 2million messages a day since mid September, with queues occasionally hitting the 1.5million messages mark without any slow down.

I would really like to get this into mainline at some point.

What do you guys think?

### CODE REVIEW

**Comment by andreimaxim** [comment]
I'll take a look at the code, hopefully during the weekend, and let you guys know.

Thanks for contributing!

**Comment by andreimaxim** [comment]
Could you guys add  some tests to your code changes? I know that sometimes it's a pain to write tests for Starling, but we should document these changes somehow.

**Comment by tomlea** [comment]
Indeed, I was fairly shocked by how little is already tested. Glad you pushed back on that!

Do you wan't me to split the various fixes into separate pull requests/branches?

Are these all features suitable for mainline?

**Comment by tomlea** [comment]
I've split this pull request into separate feature branches.

**Pull request closed without merging**
